CREATE DATABASE SAUR;

USE SAUR;

CREATE TABLE ESTATUS_CAMIONES(
    ID_ESTATUS_CAMIONES INT(11) PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(30),
    /* ACTIVO =  MANTENIMIENTO, OCUPADO, DESOCUPADO. INACTIVO */
    ESTATUS INT
    /* ACTIVO / INACTIVO */
);

INSERT INTO ESTATUS_CAMIONES (DESCRIPCION,ESTATUS) VALUES("TALLER",1);
INSERT INTO ESTATUS_CAMIONES (DESCRIPCION,ESTATUS) VALUES("LIBRE",1);
INSERT INTO ESTATUS_CAMIONES (DESCRIPCION,ESTATUS) VALUES("CARGADO",1);
INSERT INTO ESTATUS_CAMIONES (DESCRIPCION,ESTATUS) VALUES("RUTA",1);

CREATE TABLE ESTATUS_CONDUCTORES(
    ID_ESTATUS_CONDUCTORES INT(11) PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(30),
    ESTATUS INT
);

INSERT INTO ESTATUS_CONDUCTORES (DESCRIPCION,ESTATUS) VALUES("INACTIVO",1);
INSERT INTO ESTATUS_CONDUCTORES (DESCRIPCION,ESTATUS) VALUES("ACTIVO",1);

CREATE TABLE CONDUCTORES(
    ID_CONDUCTORES INT(11) PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(100) NOT NULL,
    -- FECHA_NACIMIENTO DATE NOT NULL,
    -- CURP VARCHAR(100) NOT NULL,
    -- DIRECCION TEXT NOT NULL,
    NUMERO_LICENCIA VARCHAR(100) NOT NULL,
    -- ANTIGUEDAD INT NOT NULL,
    ID_ESTATUS_CONDUCTORES INT NOT NULL,
    FOREIGN KEY (ID_ESTATUS_CONDUCTORES) REFERENCES ESTATUS_CONDUCTORES(ID_ESTATUS_CONDUCTORES) ON UPDATE CASCADE ON DELETE CASCADE,
    ID_SUCURSALES INT NOT NULL,
    FOREIGN KEY (ID_SUCURSALES) REFERENCES sucursales(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CAMIONES(
    ID_CAMIONES INT(11) PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100),
    NUMERO_SERIE VARCHAR(100),
    NUMERO_PLACAS VARCHAR(100),
    NOMBRE_CAMION VARCHAR(100),
    MODELO VARCHAR(300),
    -- CAPACIDAD_CARGA INT,
    -- ANTIGUEDAD INT,
    TIPO_CAMION VARCHAR(100),

    ESTATUS_CAMIONES VARCHAR(100),
    -- ID_ESTATUS_CAMIONES INT,
    -- FOREIGN KEY (ID_ESTATUS_CAMIONES) REFERENCES ESTATUS_CAMIONES(ID_ESTATUS_CAMIONES),

    ID_CONDUCTORES INT,
    FOREIGN KEY (ID_CONDUCTORES) REFERENCES CONDUCTORES(ID_CONDUCTORES) ON UPDATE CASCADE ON DELETE CASCADE,

    ID_SUCURSALES INT NOT NULL,
    FOREIGN KEY (ID_SUCURSALES) REFERENCES sucursales(id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- INSERT INTO CONDUCTORES (NOMBRE,APELLIDOS,TELEFONO,NUMERO_LICENCIA,ID_ESTATUS_CONDUCTORES,ID_SUCURSALES) VALUES ("NINGUNO","NINGUNO","NINGUNO","NINGUNO",2,1);

CREATE TABLE REFACCIONES(
    ID_REFACCIONES INT(11) PRIMARY KEY AUTO_INCREMENT,
    CODIGO VARCHAR(80),
    NOMBRE VARCHAR(200),
    CANTIDAD INT,
    DESCRIPCION TEXT
);

CREATE TABLE VIAJE(
    ID_VIAJE INT(11) PRIMARY KEY AUTO_INCREMENT,
    ID_CAMIONES INT,
    FOREIGN KEY (ID_CAMIONES) REFERENCES CAMIONES(ID_CAMIONES) ON UPDATE CASCADE ON DELETE CASCADE,
    TIPO_VIAJE VARCHAR(100),
    CANTIDAD_PEDIDOS VARCHAR(100),
    MONTO_TOTAL VARCHAR(100),
    -- ID_REFACCIONES INT,
    -- FOREIGN KEY (ID_REFACCIONES) REFERENCES REFACCIONES(ID_REFACCIONES) ON UPDATE CASCADE ON DELETE CASCADE,
    DESCRIPCION TEXT,
    FECHA_SALIDA DATE,
    ESTATUS INT
);


-- CREATE TABLE (
--     ID_VIAJE INT(11) PRIMARY KEY AUTO_INCREMENT,
--     ID_CAMIONES INT,
--     FOREIGN KEY (ID_CAMIONES) REFERENCES CAMIONES(ID_CAMIONES) ON UPDATE CASCADE ON DELETE CASCADE,
--     TIPO_VIAJE VARCHAR(100),
--     CANTIDAD_PEDIDOS VARCHAR(100),
--     MONTO_TOTAL VARCHAR(100),
--     -- ID_REFACCIONES INT,
--     -- FOREIGN KEY (ID_REFACCIONES) REFERENCES REFACCIONES(ID_REFACCIONES) ON UPDATE CASCADE ON DELETE CASCADE,
--     DESCRIPCION TEXT,
--     FECHA_SALIDA DATE,
--     ESTATUS INT
-- );


